package com.ecowarriors.visao;

import com.ecowarriors.CEP.ViaCEP;
import com.ecowarriors.CEP.ViaCEPException;
import com.ecowarriors.Enum.Categoria;
import com.ecowarriors.Enum.StatusDenuncia;
import com.ecowarriors.ferramentas.ConexaoBD;
import com.ecowarriors.modelos.Denuncia;
import com.ecowarriors.modelos.Endereco;
import com.ecowarriors.modelos.Usuarios;
import com.ecowarriors.persistencia.DenunciaDao;
import com.ecowarriors.persistencia.IDenunciaDao;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class tUsuarioLogado extends javax.swing.JFrame {

    private Connection conexao = null;

    public tUsuarioLogado() {
        try {
            conexao = ConexaoBD.getConexao();
            initComponents();
            setLocationRelativeTo(null);

            jTextField1_nomeCompleto.setEnabled(false);
            jTextField1_Email.setEnabled(false);
            jFormattedTextField1_Telefone.setEnabled(false);
            jFormattedTextField1_CPF.setEnabled(false);
            jLabel23.setVisible(false);
            jTextField1_possivel_criminoso.setVisible(false);

            jTextArea1_descricao.setLineWrap(true);
            jTextArea1_descricao.setWrapStyleWord(true);
            
        } catch (Exception ex) {
            Logger.getLogger(tUsuarioLogado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ExportarDados(Usuarios usuario) {
        jTextField1_Email.setText(usuario.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1_PERFIL = new javax.swing.JMenuItem();
        jMenuItem2_SAIR = new javax.swing.JMenuItem();
        jFrame1_perfilUsuario = new javax.swing.JFrame();
        jFormattedTextField1_CPF = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1_nomeCompleto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField1_Telefone = new javax.swing.JFormattedTextField();
        jTextField1_Email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFrame1_CadastrarDenuncia = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jFormattedTextField1_CEP = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField1_Municipios = new javax.swing.JTextField();
        jTextField1_possivel_criminoso = new javax.swing.JTextField();
        jTextField1_pontoReferencia = new javax.swing.JTextField();
        jTextField1_rua = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField1_bairro = new javax.swing.JTextField();
        jButton3_denunciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_descricao = new javax.swing.JTextArea();
        jFormattedTextField1_data = new javax.swing.JFormattedTextField();
        jRadioButton1_simm = new javax.swing.JRadioButton();
        jRadioButton2_naoo = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1_PERFIL.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jMenuItem1_PERFIL.setForeground(new java.awt.Color(0, 102, 0));
        jMenuItem1_PERFIL.setText("PERFIL");
        jMenuItem1_PERFIL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1_PERFIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1_PERFILMouseClicked(evt);
            }
        });
        jMenuItem1_PERFIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_PERFILActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1_PERFIL);

        jMenuItem2_SAIR.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jMenuItem2_SAIR.setForeground(new java.awt.Color(0, 102, 0));
        jMenuItem2_SAIR.setText("SAIR");
        jMenuItem2_SAIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2_SAIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2_SAIRMouseClicked(evt);
            }
        });
        jMenuItem2_SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_SAIRActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2_SAIR);

        jFrame1_perfilUsuario.setUndecorated(true);
        jFrame1_perfilUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFormattedTextField1_CPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jFormattedTextField1_CPF.setForeground(new java.awt.Color(0, 102, 0));
        try {
            jFormattedTextField1_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_CPF.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jFrame1_perfilUsuario.getContentPane().add(jFormattedTextField1_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 230, 40));

        jLabel12.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 0));
        jLabel12.setText("CPF");
        jFrame1_perfilUsuario.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 60, 40));

        jLabel13.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 0));
        jLabel13.setText("NOME COMPLETO");
        jFrame1_perfilUsuario.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 250, 40));

        jTextField1_nomeCompleto.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_nomeCompleto.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_nomeCompleto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jTextField1_nomeCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_nomeCompletoKeyPressed(evt);
            }
        });
        jFrame1_perfilUsuario.getContentPane().add(jTextField1_nomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 440, 40));

        jLabel14.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setText("TELEFONE");
        jFrame1_perfilUsuario.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 270, 150, 40));

        jFormattedTextField1_Telefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jFormattedTextField1_Telefone.setForeground(new java.awt.Color(0, 102, 0));
        try {
            jFormattedTextField1_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_Telefone.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jFrame1_perfilUsuario.getContentPane().add(jFormattedTextField1_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 270, 230, 40));

        jTextField1_Email.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_Email.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_Email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jFrame1_perfilUsuario.getContentPane().add(jTextField1_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 590, 40));

        jLabel17.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 0));
        jLabel17.setText("EMAIL");
        jFrame1_perfilUsuario.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 100, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/logoEcoWarriorsTelas.png"))); // NOI18N
        jFrame1_perfilUsuario.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 20, 200, 200));

        jLabel19.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 0));
        jLabel19.setText("ALTERAR SENHA");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFrame1_perfilUsuario.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "DADOS LOGIN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 32), new java.awt.Color(0, 102, 0))); // NOI18N
        jFrame1_perfilUsuario.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 830, 170));

        jButton2.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/voltar.png"))); // NOI18N
        jButton2.setText("  VOLTAR");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame1_perfilUsuario.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 770, 190, 50));

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "DADOS PESSOAIS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 32), new java.awt.Color(0, 102, 0))); // NOI18N
        jFrame1_perfilUsuario.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 830, 170));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/5333978.jpg"))); // NOI18N
        jFrame1_perfilUsuario.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        jFrame1_CadastrarDenuncia.setUndecorated(true);
        jFrame1_CadastrarDenuncia.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/logoEcoWarriorsTelas.png"))); // NOI18N
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 20, 200, 200));

        jLabel20.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 0));
        jLabel20.setText("DESCRIÇÃO");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 240, 170, 30));

        jLabel21.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setText("CADASTRAR DENÚNCIA");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 430, 50));

        jFormattedTextField1_CEP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jFormattedTextField1_CEP.setForeground(new java.awt.Color(0, 102, 0));
        try {
            jFormattedTextField1_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_CEP.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jFrame1_CadastrarDenuncia.getContentPane().add(jFormattedTextField1_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 190, 40));

        jLabel22.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 0));
        jLabel22.setText("RUA");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 60, 40));

        jTextField1_Municipios.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_Municipios.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_Municipios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jFrame1_CadastrarDenuncia.getContentPane().add(jTextField1_Municipios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 340, 40));

        jTextField1_possivel_criminoso.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_possivel_criminoso.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_possivel_criminoso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jFrame1_CadastrarDenuncia.getContentPane().add(jTextField1_possivel_criminoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 580, 40));

        jTextField1_pontoReferencia.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_pontoReferencia.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_pontoReferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jFrame1_CadastrarDenuncia.getContentPane().add(jTextField1_pontoReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 580, 40));

        jTextField1_rua.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_rua.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jFrame1_CadastrarDenuncia.getContentPane().add(jTextField1_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 340, 40));

        jButton3.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/voltar.png"))); // NOI18N
        jButton3.setText("  VOLTAR");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1_CadastrarDenuncia.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 770, 190, 50));

        jLabel23.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 0));
        jLabel23.setText("POSSÍVEL CRIMINOSO");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 530, 310, -1));

        jLabel24.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 0));
        jLabel24.setText("RECONHECE O AUTOR DO CRIME?");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 480, -1));

        jLabel25.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 0));
        jLabel25.setText("DATA DO OCORRIDO");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 290, -1));

        jLabel26.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 0));
        jLabel26.setText("PONTO DE REFERÊNCIA");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 340, 30));

        jLabel27.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 0));
        jLabel27.setText("BAIRRO");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 120, 40));

        jLabel28.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 0));
        jLabel28.setText("CEP");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 70, 40));

        jButton1.setFont(new java.awt.Font("Serif", 3, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/lupa.png"))); // NOI18N
        jButton1.setText(" BUSCAR");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jFrame1_CadastrarDenuncia.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 140, 40));

        jLabel29.setFont(new java.awt.Font("Serif", 3, 28)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 0));
        jLabel29.setText("MUNICIPIO");
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 160, 40));

        jTextField1_bairro.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextField1_bairro.setForeground(new java.awt.Color(0, 102, 0));
        jTextField1_bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jFrame1_CadastrarDenuncia.getContentPane().add(jTextField1_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 340, 40));

        jButton3_denunciar.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        jButton3_denunciar.setForeground(new java.awt.Color(0, 102, 0));
        jButton3_denunciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/cadastroDenuncias.png"))); // NOI18N
        jButton3_denunciar.setText("  DENUNCIAR");
        jButton3_denunciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3_denunciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3_denunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_denunciarActionPerformed(evt);
            }
        });
        jFrame1_CadastrarDenuncia.getContentPane().add(jButton3_denunciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 230, 70));

        jTextArea1_descricao.setColumns(20);
        jTextArea1_descricao.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jTextArea1_descricao.setForeground(new java.awt.Color(0, 102, 0));
        jTextArea1_descricao.setRows(5);
        jTextArea1_descricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextArea1_descricao);

        jFrame1_CadastrarDenuncia.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 580, 100));

        jFormattedTextField1_data.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jFormattedTextField1_data.setForeground(new java.awt.Color(0, 102, 0));
        try {
            jFormattedTextField1_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1_data.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jFrame1_CadastrarDenuncia.getContentPane().add(jFormattedTextField1_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, 130, 40));

        jRadioButton1_simm.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jRadioButton1_simm.setForeground(new java.awt.Color(0, 102, 0));
        jRadioButton1_simm.setText("SIM");
        jRadioButton1_simm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_simmActionPerformed(evt);
            }
        });
        jFrame1_CadastrarDenuncia.getContentPane().add(jRadioButton1_simm, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, -1, -1));

        jRadioButton2_naoo.setFont(new java.awt.Font("Serif", 3, 26)); // NOI18N
        jRadioButton2_naoo.setForeground(new java.awt.Color(0, 102, 0));
        jRadioButton2_naoo.setText("NÃO");
        jRadioButton2_naoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_naooActionPerformed(evt);
            }
        });
        jFrame1_CadastrarDenuncia.getContentPane().add(jRadioButton2_naoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 490, -1, -1));

        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "DADOS DO INCIDENTE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 24), new java.awt.Color(0, 102, 0))); // NOI18N
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 620, 450));

        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "ENDEREÇO DO INCIDENTE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Serif", 3, 24), new java.awt.Color(0, 102, 0))); // NOI18N
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 620, 450));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/5333978.jpg"))); // NOI18N
        jFrame1_CadastrarDenuncia.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/consultarDenuncia.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 135, 140));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("CONSULTAR DENÚNCIA ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 680, 400, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/novaDenuncia.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 135, 140));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/logoPrincipall.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 0, 310, 300));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("NOVA DENÚNCIA");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 290, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/usuarioLogadoFundoPreto.png"))); // NOI18N
        jLabel2.setComponentPopupMenu(jPopupMenu1);
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 60, -1, -1));

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "OPÇÕES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 3, 24), new java.awt.Color(0, 102, 0))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 430, 440));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/setinhaBaixo.png"))); // NOI18N
        jLabel9.setComponentPopupMenu(jPopupMenu1);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 90, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ecowarriors/visao/icons/5333978.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jLabel2.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    // Exibe o JPopupMenu no local onde o mouse foi pressionado
                    jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem1_PERFILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_PERFILActionPerformed
        try {

            jFrame1_perfilUsuario.setVisible(true);
            jFrame1_perfilUsuario.setBounds(WIDTH, WIDTH, 1600, 900);
            jFrame1_perfilUsuario.setLocationRelativeTo(null);
            this.setVisible(false);
            buscarDadosUsuarioLogado();
            BuscarDadosUsuarioEmail();
        } catch (SQLException ex) {
            Logger.getLogger(tUsuarioLogado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1_PERFILActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        jLabel9.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    // Exibe o JPopupMenu no local onde o mouse foi pressionado
                    jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }//GEN-LAST:event_jLabel9MouseClicked

    public void buscarDadosUsuarioLogado() throws SQLException {
        String cpf = jTextField1_Email.getText();
        String sql = "SELECT * from usuarios where cpf = ?";
        try ( PreparedStatement preparedStatement = conexao.prepareStatement(sql)) {
            preparedStatement.setString(1, cpf);
            try ( ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    String nome = resultSet.getString("nome");
                    jTextField1_nomeCompleto.setText(nome);
                    String email = resultSet.getString("email");
                    jTextField1_Email.setText(email);
                    String telefone = resultSet.getString("telefone");
                    jFormattedTextField1_CPF.setText(cpf);
                    jFormattedTextField1_Telefone.setText(telefone);
                } else {

                }
            }
        }
    }

    public void BuscarDadosUsuarioEmail() throws SQLException {
        String email = jTextField1_Email.getText();
        String sql = "SELECT * from usuarios where EMAIL = ?";
        try ( PreparedStatement preparedStatement = conexao.prepareStatement(sql)) {
            preparedStatement.setString(1, email);
            try ( ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    String nome = resultSet.getString("nome");
                    jTextField1_nomeCompleto.setText(nome);
                    String emailL = resultSet.getString("email");
                    jTextField1_Email.setText(emailL);
                    String cpf = resultSet.getString("cpf");
                    jFormattedTextField1_CPF.setText(cpf);
                    String telefone = resultSet.getString("telefone");
                    jFormattedTextField1_Telefone.setText(telefone);
                } else {

                }
            }
        }
    }

    private void jMenuItem2_SAIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2_SAIRMouseClicked

    }//GEN-LAST:event_jMenuItem2_SAIRMouseClicked

    private void jMenuItem2_SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_SAIRActionPerformed
        tLoginDenunciantes loginDenunciante = new tLoginDenunciantes();
        loginDenunciante.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2_SAIRActionPerformed

    private void jTextField1_nomeCompletoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_nomeCompletoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_nomeCompletoKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrame1_perfilUsuario.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jFrame1_CadastrarDenuncia.setBounds(WIDTH, WIDTH, 1600, 900);
        jFrame1_CadastrarDenuncia.setLocationRelativeTo(null);
        jFrame1_CadastrarDenuncia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        jFrame1_CadastrarDenuncia.setBounds(WIDTH, WIDTH, 1600, 900);
        jFrame1_CadastrarDenuncia.setLocationRelativeTo(null);
        jFrame1_CadastrarDenuncia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(true);
        jFrame1_CadastrarDenuncia.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ViaCEP cep = new ViaCEP();
            cep.buscar(jFormattedTextField1_CEP.getText());
            jTextField1_bairro.setText(cep.getBairro());
            jTextField1_rua.setText(cep.getLogradouro());
            jTextField1_Municipios.setText(cep.getLocalidade());

        } catch (ViaCEPException ex) {
            Logger.getLogger(tCadastroDenunciante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3_denunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_denunciarActionPerformed
        try {
            File fotos = new File("./src\\main\\java\\com\\ecowarriors\\images\\logoEcoWarriorsTelas.png");
            String cpfUsuario = jFormattedTextField1_CPF.getText().replace(".", "").replace("-", "");
            
            if (jRadioButton1_simm.isSelected()) {
                IDenunciaDao denunciaDAO = new DenunciaDao();
                Endereco endereco = new Endereco(jTextField1_rua.getText(), jTextField1_bairro.getText(), jTextField1_Municipios.getText(), jFormattedTextField1_CEP.getText(),
                        jTextField1_pontoReferencia.getText());
                DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                java.sql.Date data = null;
                data = new java.sql.Date(formatter.parse(jFormattedTextField1_data.getText()).getTime());
                Denuncia denuncia = new Denuncia("", fotos, cpfUsuario, jTextArea1_descricao.getText(), Categoria.FLORA, data, jTextField1_possivel_criminoso.getText(), StatusDenuncia.CRIADA);

                denunciaDAO.cadastroDenuncia(denuncia, endereco);
                JOptionPane.showMessageDialog(rootPane, "Denuncia cadastrado com sucesso!");
                limparCamposDenuncia();
            } else if (jRadioButton2_naoo.isSelected()) {

                IDenunciaDao denunciaDAO = new DenunciaDao();
                Endereco enderecoo = new Endereco(jTextField1_rua.getText(), jTextField1_bairro.getText(), jTextField1_Municipios.getText(), jFormattedTextField1_CEP.getText(),
                        jTextField1_pontoReferencia.getText());
                DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                java.sql.Date data = null;
                data = new java.sql.Date(formatter.parse(jFormattedTextField1_data.getText()).getTime());
                Denuncia denunciaa = new Denuncia("", fotos, cpfUsuario, jTextArea1_descricao.getText(), Categoria.FLORA, data, "Nao_identificado", StatusDenuncia.CRIADA);
                denunciaDAO.cadastroDenuncia(denunciaa, enderecoo);
                JOptionPane.showMessageDialog(rootPane, "Denuncia cadastrado com sucesso!");
                limparCamposDenuncia();
                
            }
        } catch (Exception ex) {
            Logger.getLogger(tCadastroDenunciante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3_denunciarActionPerformed

    private void limparCamposDenuncia() {
        jTextArea1_descricao.setText("");
        jFormattedTextField1_CEP.setText("");
        jTextField1_bairro.setText("");
        jTextField1_Municipios.setText("");
        jTextField1_possivel_criminoso.setText("");
        jTextField1_pontoReferencia.setText("");
        jFormattedTextField1_data.setText("");
        jTextField1_rua.setText("");
        jRadioButton1_simm.setSelected(false);
        jRadioButton2_naoo.setSelected(false);
        jLabel23.setVisible(false);
        jTextField1_possivel_criminoso.setVisible(false);

    }

    private void jRadioButton1_simmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_simmActionPerformed
        if (jRadioButton1_simm.isSelected()) {
            jLabel23.setVisible(true);
            jTextField1_possivel_criminoso.setVisible(true);
            jRadioButton2_naoo.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1_simmActionPerformed

    private void jRadioButton2_naooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_naooActionPerformed
        if (jRadioButton2_naoo.isSelected()) {
            jLabel23.setVisible(false);
            jTextField1_possivel_criminoso.setVisible(false);
            jRadioButton1_simm.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2_naooActionPerformed

    private void jMenuItem1_PERFILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1_PERFILMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_PERFILMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tUsuarioLogado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tUsuarioLogado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tUsuarioLogado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tUsuarioLogado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tUsuarioLogado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3_denunciar;
    private javax.swing.JFormattedTextField jFormattedTextField1_CEP;
    private javax.swing.JFormattedTextField jFormattedTextField1_CPF;
    private javax.swing.JFormattedTextField jFormattedTextField1_Telefone;
    private javax.swing.JFormattedTextField jFormattedTextField1_data;
    private javax.swing.JFrame jFrame1_CadastrarDenuncia;
    private javax.swing.JFrame jFrame1_perfilUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1_PERFIL;
    private javax.swing.JMenuItem jMenuItem2_SAIR;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1_simm;
    private javax.swing.JRadioButton jRadioButton2_naoo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1_descricao;
    private javax.swing.JTextField jTextField1_Email;
    private javax.swing.JTextField jTextField1_Municipios;
    private javax.swing.JTextField jTextField1_bairro;
    private javax.swing.JTextField jTextField1_nomeCompleto;
    private javax.swing.JTextField jTextField1_pontoReferencia;
    private javax.swing.JTextField jTextField1_possivel_criminoso;
    private javax.swing.JTextField jTextField1_rua;
    // End of variables declaration//GEN-END:variables
}
